Vuex Beta 0.13
Fixed Vuex bug that was causing the following error.
local dev server:
state.set is undefined
Netlify Server:
    TypeError: t.set is undefined